port: 8080
token: "59f620ef37baa697fc95177404e58106"
discount:
  expire_time : 5
  code_length: 8
postgres:
  POSTGRES_HOST: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "password"
  POSTGRES_DB: "payment"
  POSTGRES_PORT: 5432
  TIMEZONE: "Asia/Tehran"

